from pathlib import Path

p = Path('IronNestFCS.Logic/FSC.cs')
s = p.read_text(encoding='utf-8-sig')

def replace_once(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f'{label}: anchor not found')
    s = s.replace(old, new, 1)

replace_once(
'''    private ArtilleryTask? _firePriorityWinner;\n    private ArtilleryTask? _firePrioritySecond;\n    private ArtilleryTask? _fireLaneCommittedTask;\n''',
'''    private ArtilleryTask? _firePriorityWinner;\n    private ArtilleryTask? _firePrioritySecond;\n    // The turret-lane owner may still be preempted while it is only slewing/holding azimuth.\n    // _fireLaneCommittedTask is the later hard-commit boundary immediately before Review Console work.\n    private ArtilleryTask? _turretLaneOwnerTask;\n    private ArtilleryTask? _fireLaneCommittedTask;\n''',
'priority fields')

replace_once(
'''        _firePriorityWinner = null;\n        _firePrioritySecond = null;\n        _fireLaneCommittedTask = null;\n''',
'''        _firePriorityWinner = null;\n        _firePrioritySecond = null;\n        _turretLaneOwnerTask = null;\n        _fireLaneCommittedTask = null;\n''',
'reset owner')

old = '''    /// <summary>\n    /// Unified cleanup for an abnormal task exit. This deliberately does NOT bump the global generation:\n    /// F9/Dispose use ResetFirePriorityTracking() for that. Local failures must invalidate the broken pair\n    /// without killing a healthy task on the other gun. The failed task's candidate/session/order is removed,\n    /// while an already committed or fixed non-provisional winner on the other gun is preserved.\n    /// </summary>\n    private void InvalidateFirePriorityForAbnormalTask(ArtilleryTask task, string reason) {\n        var preservedWinner = _firePriorityWinner != null\n                              && !ReferenceEquals(_firePriorityWinner, task)\n                              && IsActiveTask(_firePriorityWinner)\n                              && (!_firePriorityWinnerProvisional\n                                  || ReferenceEquals(_fireLaneCommittedTask, _firePriorityWinner))\n            ? _firePriorityWinner\n            : null;\n\n        if (_leftFireCandidate != null && ReferenceEquals(_leftFireCandidate.Task, task))\n            _leftFireCandidate = null;\n        if (_rightFireCandidate != null && ReferenceEquals(_rightFireCandidate.Task, task))\n            _rightFireCandidate = null;\n        if (_leftFireCandidate != null && !ReferenceEquals(_leftFireCandidate.Task, LeftTask))\n            _leftFireCandidate = null;\n        if (_rightFireCandidate != null && !ReferenceEquals(_rightFireCandidate.Task, RightTask))\n            _rightFireCandidate = null;\n\n        _firePrioritySession = null;\n        _firePriorityWinner = preservedWinner;\n        _firePrioritySecond = null;\n        _firePriorityWinnerProvisional = false;\n        _firePriorityLeftDetail = \"\";\n        _firePriorityRightDetail = \"\";\n        _firePriorityOrderText = \"\";\n\n        if (preservedWinner != null) {\n            if (!ReferenceEquals(_fireLaneCommittedTask, preservedWinner))\n                _fireLaneCommittedTask = null;\n            _firePriorityStatusText =\n                $\"首发仲裁：异常清理（{reason}），保持 T{preservedWinner.targetId} 优先\";\n        }\n        else {\n            if (ReferenceEquals(_fireLaneCommittedTask, task)\n                || _fireLaneCommittedTask == null\n                || !IsActiveTask(_fireLaneCommittedTask)) {\n                _fireLaneCommittedTask = null;\n            }\n            _firePriorityStatusText = $\"首发仲裁：已清理（{reason}）\";\n        }\n\n        MelonLogger.Warning(\n            $\"[FCS] Fire arbitration invalidated by T{task.targetId}: {reason}; \" +\n            $\"preservedWinner={(preservedWinner == null ? \"none\" : $\"T{preservedWinner.targetId}\")}\");\n    }\n'''
new = '''    /// <summary>\n    /// Unified cleanup for an abnormal task exit. This deliberately does NOT bump the global generation:\n    /// F9/Dispose use ResetFirePriorityTracking() for that. Local failures must invalidate the broken pair\n    /// without killing a healthy task on the other gun. A healthy winner is preserved together with whether\n    /// it is still provisional; only the later Review/Arm hard-commit is non-preemptible.\n    /// </summary>\n    private void InvalidateFirePriorityForAbnormalTask(ArtilleryTask task, string reason) {\n        var preservedWinner = _firePriorityWinner != null\n                              && !ReferenceEquals(_firePriorityWinner, task)\n                              && IsActiveTask(_firePriorityWinner)\n            ? _firePriorityWinner\n            : null;\n        var preservedWinnerProvisional = preservedWinner != null && _firePriorityWinnerProvisional;\n\n        if (_leftFireCandidate != null && ReferenceEquals(_leftFireCandidate.Task, task))\n            _leftFireCandidate = null;\n        if (_rightFireCandidate != null && ReferenceEquals(_rightFireCandidate.Task, task))\n            _rightFireCandidate = null;\n        if (_leftFireCandidate != null && !ReferenceEquals(_leftFireCandidate.Task, LeftTask))\n            _leftFireCandidate = null;\n        if (_rightFireCandidate != null && !ReferenceEquals(_rightFireCandidate.Task, RightTask))\n            _rightFireCandidate = null;\n\n        _firePrioritySession = null;\n        _firePriorityWinner = preservedWinner;\n        _firePrioritySecond = null;\n        _firePriorityWinnerProvisional = preservedWinnerProvisional;\n        _firePriorityLeftDetail = \"\";\n        _firePriorityRightDetail = \"\";\n        _firePriorityOrderText = \"\";\n\n        if (ReferenceEquals(_turretLaneOwnerTask, task)\n            || (_turretLaneOwnerTask != null && !IsActiveTask(_turretLaneOwnerTask))) {\n            _turretLaneOwnerTask = null;\n        }\n\n        if (preservedWinner != null) {\n            if (!ReferenceEquals(_fireLaneCommittedTask, preservedWinner))\n                _fireLaneCommittedTask = null;\n            _firePriorityStatusText = preservedWinnerProvisional\n                ? $\"首发仲裁：异常清理（{reason}），保持 T{preservedWinner.targetId} 临时优先\"\n                : $\"首发仲裁：异常清理（{reason}），保持 T{preservedWinner.targetId} 优先\";\n        }\n        else {\n            if (ReferenceEquals(_fireLaneCommittedTask, task)\n                || _fireLaneCommittedTask == null\n                || !IsActiveTask(_fireLaneCommittedTask)) {\n                _fireLaneCommittedTask = null;\n            }\n            _firePriorityStatusText = $\"首发仲裁：已清理（{reason}）\";\n        }\n\n        MelonLogger.Warning(\n            $\"[FCS] Fire arbitration invalidated by T{task.targetId}: {reason}; \" +\n            $\"preservedWinner={(preservedWinner == null ? \"none\" : $\"T{preservedWinner.targetId}\")}\");\n    }\n'''
replace_once(old, new, 'abnormal cleanup')

old = '''    private void OnTaskAssignedForFirePriority() {\n        if (_fireLaneCommittedTask != null || LeftTask == null || RightTask == null)\n            return;\n\n        // Only a provisional single-gun winner may be reopened. A promoted second shot from an already-arbitrated\n        // pair is fixed and must stay ahead of any freshly dispatched task, even while the other gun recovers.\n        if (_firePriorityWinner != null\n            && _firePriorityWinnerProvisional\n            && _firePrioritySecond == null\n            && GetCandidateForTask(_firePriorityWinner) != null\n            && CanArbitrateCurrentTasks()) {\n            var previousWinner = _firePriorityWinner;\n            _firePriorityWinner = null;\n            _firePriorityWinnerProvisional = false;\n            MelonLogger.Msg(\n                $\"[FCS] T{previousWinner.targetId}: second synchronized task arrived before fire-lane commit; reopening arbitration\");\n            OpenFirePrioritySession(\"second synchronized task assigned before fire-lane commit\");\n            return;\n        }\n\n        if (_firePriorityWinner == null && _firePrioritySession == null) {\n            var left = GetCurrentCandidate(LeftRight.Left);\n            var right = GetCurrentCandidate(LeftRight.Right);\n            if ((left != null || right != null) && CanArbitrateCurrentTasks())\n                OpenFirePrioritySession(\"task assignment completed a synchronized pair\");\n        }\n    }\n'''
new = '''    private void OnTaskAssignedForFirePriority() {\n        if (_fireLaneCommittedTask != null || LeftTask == null || RightTask == null)\n            return;\n\n        // Assignment alone is not enough reason to interrupt a provisional turret owner. Let it keep slewing\n        // while the newly assigned task performs its real ballistic solve; RegisterBallisticSolution reopens\n        // arbitration only when that second candidate actually exists.\n        if (_firePriorityWinner == null && _firePrioritySession == null) {\n            var left = GetCurrentCandidate(LeftRight.Left);\n            var right = GetCurrentCandidate(LeftRight.Right);\n            if ((left != null || right != null) && CanArbitrateCurrentTasks())\n                OpenFirePrioritySession(\"task assignment completed a synchronized pair\");\n        }\n    }\n'''
replace_once(old, new, 'task assigned arbitration')

s = s.replace(
'''            // If a single-gun winner has not actually committed the shared turret yet, a newly solved second task\n            // still belongs to the same synchronized preparation round. Reopen Promise.all-style arbitration.\n''',
'''            // Until Review/Arm hard-commit, even a promoted previous Second remains provisional. A newly solved\n            // task on the recovered gun may therefore reopen arbitration while the current winner is still slewing.\n''',
1)
s = s.replace(
'''            // A committed or promoted shot is never preempted. A later solution can only become the fixed second\n            // shot behind it.\n            if (_firePrioritySecond == null && !ReferenceEquals(_firePriorityWinner, task)) {\n                _firePrioritySecond = task;\n                _firePriorityWinnerProvisional = false;\n                MelonLogger.Msg($\"[FCS] {side} T{task.targetId}: queued behind existing fire-lane owner\");\n            }\n''',
'''            // If arbitration cannot reopen (for example because the winner has already hard-committed), the\n            // new solution can only queue behind the current winner. Do not change provisional state here.\n            if (_firePrioritySecond == null && !ReferenceEquals(_firePriorityWinner, task)) {\n                _firePrioritySecond = task;\n                MelonLogger.Msg($\"[FCS] {side} T{task.targetId}: queued behind current fire priority\");\n            }\n''',
1)

replace_once(
'''        _firePriorityWinner = winner.Task;\n        _firePrioritySecond = loser.Task;\n        _firePriorityWinnerProvisional = false;\n''',
'''        _firePriorityWinner = winner.Task;\n        _firePrioritySecond = loser.Task;\n        // Pair order is still provisional until the winner has both azimuth and elevation ready and is\n        // about to touch Review Console. Before that point a later synchronized candidate may preempt it.\n        _firePriorityWinnerProvisional = true;\n''',
'pair provisional')

old = '''    private bool CommitFireLane(ArtilleryTask task, int generation) {\n        if (generation != _firePriorityGeneration\n            || !ReferenceEquals(_firePriorityWinner, task)\n            || !IsActiveTask(task))\n            return false;\n\n        _fireLaneCommittedTask = task;\n        _firePriorityWinnerProvisional = false;\n        _firePriorityStatusText = !string.IsNullOrEmpty(_firePriorityOrderText)\n            ? $\"首发仲裁：顺序锁定 {_firePriorityOrderText}\"\n            : $\"首发仲裁：T{task.targetId} 已取得共享击发权\";\n        MelonLogger.Msg($\"[FCS] T{task.targetId}: shared fire lane committed\");\n        return true;\n    }\n'''
new = '''    private bool ClaimTurretLane(ArtilleryTask task, int generation) {\n        if (generation != _firePriorityGeneration\n            || !ReferenceEquals(_firePriorityWinner, task)\n            || !IsActiveTask(task))\n            return false;\n\n        _turretLaneOwnerTask = task;\n        _firePriorityStatusText = !string.IsNullOrEmpty(_firePriorityOrderText)\n            ? $\"首发仲裁：临时顺序 {_firePriorityOrderText}（T{task.targetId} 使用方位）\"\n            : $\"首发仲裁：T{task.targetId} 临时优先（使用共享方位）\";\n        MelonLogger.Msg($\"[FCS] T{task.targetId}: shared turret lane claimed provisionally\");\n        return true;\n    }\n\n    private bool CommitFireLane(ArtilleryTask task, int generation, TurretReservation reservation) {\n        if (generation != _firePriorityGeneration\n            || !ReferenceEquals(_firePriorityWinner, task)\n            || !IsActiveTask(task)\n            || !reservation.Acquired\n            || !reservation.Ready\n            || !ReferenceEquals(_turretLaneOwnerTask, task))\n            return false;\n\n        _fireLaneCommittedTask = task;\n        reservation.HardCommitted = true;\n        _firePriorityWinnerProvisional = false;\n        _firePriorityStatusText = !string.IsNullOrEmpty(_firePriorityOrderText)\n            ? $\"首发仲裁：顺序锁定 {_firePriorityOrderText}\"\n            : $\"首发仲裁：T{task.targetId} 已取得共享击发权\";\n        MelonLogger.Msg($\"[FCS] T{task.targetId}: shared fire lane hard-committed before Review Console\");\n        return true;\n    }\n'''
replace_once(old, new, 'commit boundary')

s = s.replace(
'''        // Once a pair has been resolved and First has actually committed the shared fire lane, let the fixed\n        // Second enter CoroutineLock.Acquire() immediately. It waits behind First while that lock is held,\n        // reproducing the pre-decoupling reservation pipeline without allowing Second to rotate out of order.\n        return ReferenceEquals(_firePrioritySecond, task)\n               && _firePriorityWinner != null\n               && ReferenceEquals(_fireLaneCommittedTask, _firePriorityWinner)\n               && IsActiveTask(_firePriorityWinner);\n''',
'''        // Once First physically owns the turret lane, let Second prequeue behind the held lock immediately.\n        // Turret ownership itself is still provisional; only the later Review/Arm boundary is hard-committed.\n        return ReferenceEquals(_firePrioritySecond, task)\n               && _firePriorityWinner != null\n               && ReferenceEquals(_turretLaneOwnerTask, _firePriorityWinner)\n               && IsActiveTask(_firePriorityWinner);\n''',
1)
s = s.replace(
'''        // Event/state gate only: no scoring timeout. A resolved First may enter immediately; its fixed Second may\n        // prequeue only after First owns the lane. Reset/generation changes still cancel stale reservations.\n''',
'''        // Event/state gate only: no scoring timeout. A resolved First may enter immediately; Second may prequeue\n        // after First physically owns the turret lane. Reset/generation changes still cancel stale reservations.\n''',
1)

replace_once(
'''                _firePriorityWinner = next;\n                _firePriorityWinnerProvisional = false;\n                _firePriorityStatusText = !string.IsNullOrEmpty(_firePriorityOrderText)\n                    ? $\"首发仲裁：第二炮优先 T{next.targetId}（{_firePriorityOrderText}）\"\n                    : $\"首发仲裁：T{next.targetId} 优先\";\n                MelonLogger.Msg($\"[FCS] Fire priority: promoting T{next.targetId} after previous shot released\");\n''',
'''                _firePriorityWinner = next;\n                // The previous Second gets an immediate head start on the turret, but remains preemptible until\n                // azimuth + elevation are both ready and it hard-commits immediately before Review Console.\n                _firePriorityWinnerProvisional = true;\n                _firePriorityStatusText = !string.IsNullOrEmpty(_firePriorityOrderText)\n                    ? $\"首发仲裁：第二炮临时优先 T{next.targetId}（{_firePriorityOrderText}）\"\n                    : $\"首发仲裁：T{next.targetId} 临时优先\";\n                MelonLogger.Msg($\"[FCS] Fire priority: promoting T{next.targetId} provisionally after previous shot\");\n''',
'promoted second provisional')

old = '''        task.progress = Progress.WaitingForFire;\n        var turretWaitTimeout = _sceneInteractor.AutoFire\n            ? AutoTurretWaitTimeoutSeconds\n            : ManualTurretWaitTimeoutSeconds;\n        var turretDeadline = FcsRuntimeClock.Now + turretWaitTimeout;\n        while (true) {\n            yield return FcsRuntimeClock.WaitUntilFocused();\n            if (turret.Ready || turret.Failed) break;\n            if (FcsRuntimeClock.Now >= turretDeadline) break;\n            yield return null;\n        }\n        if (turret.Failed) {\n            AbortTask(leftRight, task, turret, turret.FailureReason);\n            yield break;\n        }\n        if (!turret.Ready) {\n            AbortTask(leftRight, task, turret, $\"turret reservation timed out after {turretWaitTimeout:F0}s\");\n            yield break;\n        }\n\n        try {\n'''
new = '''        task.progress = Progress.WaitingForFire;\n        var turretWaitTimeout = _sceneInteractor.AutoFire\n            ? AutoTurretWaitTimeoutSeconds\n            : ManualTurretWaitTimeoutSeconds;\n        var turretDeadline = FcsRuntimeClock.Now + turretWaitTimeout;\n\n        // Hard commit only after BOTH local elevation and shared azimuth are physically ready. Until this exact\n        // boundary, a provisional winner (including a promoted previous Second) may lose re-arbitration and its\n        // live TurretReservation will release/requeue the shared turret without touching Review/Arm controls.\n        while (true) {\n            while (true) {\n                yield return FcsRuntimeClock.WaitUntilFocused();\n                if (turret.Ready || turret.Failed) break;\n                if (FcsRuntimeClock.Now >= turretDeadline) break;\n                yield return null;\n            }\n            if (turret.Failed) {\n                AbortTask(leftRight, task, turret, turret.FailureReason);\n                yield break;\n            }\n            if (!turret.Ready && FcsRuntimeClock.Now >= turretDeadline) {\n                AbortTask(leftRight, task, turret, $\"turret reservation timed out after {turretWaitTimeout:F0}s\");\n                yield break;\n            }\n\n            if (CommitFireLane(task, taskGeneration, turret))\n                break;\n\n            // Arbitration changed between Ready observation and commit. Do not touch shared fire controls; wait\n            // for this task to win again and reacquire/reach its azimuth normally.\n            yield return null;\n        }\n\n        try {\n'''
replace_once(old, new, 'hard commit before review')

replace_once(
'''        public bool Ready;\n        public bool Failed;\n        public bool Canceled;\n        public bool Released;\n''',
'''        public bool Ready;\n        public bool Failed;\n        public bool Canceled;\n        public bool Released;\n        public bool HardCommitted;\n''',
'turret reservation hard flag')

s = s.replace(
'''            // First and the already-fixed Second can both reach this Acquire. First gets the free lock; Second\n            // reaches it only after First has committed, so it waits behind the held lock and is ready to take over\n            // immediately after a confirmed shot releases it.\n            res.Released = false;\n            res.Acquired = false;\n''',
'''            // First and Second can both reach this Acquire. First gets the free lock; Second may prequeue once\n            // First physically owns the turret, so it is ready to take over immediately after lock release.\n            res.Released = false;\n            res.Acquired = false;\n            res.Ready = false;\n            res.HardCommitted = false;\n''',
1)

replace_once(
'''            if (!CommitFireLane(task, res.Generation)) {\n                ReleaseTurretOnce(res);\n                yield return null;\n                continue;\n            }\n''',
'''            if (!ClaimTurretLane(task, res.Generation)) {\n                ReleaseTurretOnce(res);\n                yield return null;\n                continue;\n            }\n''',
'claim turret lane')

replace_once(
'''            res.Ready = true;\n            yield break;\n''',
'''            res.Ready = true;\n\n            // Keep the reservation coroutine alive after azimuth reaches target. If this provisional owner loses\n            // arbitration before the main task hard-commits, release the turret and re-enter the normal queue.\n            // This also covers the case where azimuth finishes before the gun's own elevation is ready.\n            while (!res.Canceled\n                   && res.Generation == _firePriorityGeneration\n                   && IsActiveTask(task)\n                   && !res.HardCommitted\n                   && ReferenceEquals(_firePriorityWinner, task)) {\n                yield return FcsRuntimeClock.WaitUntilFocused();\n                yield return null;\n            }\n\n            if (res.HardCommitted)\n                yield break;\n\n            res.Ready = false;\n            ReleaseTurretOnce(res);\n            if (res.Canceled || res.Generation != _firePriorityGeneration || !IsActiveTask(task))\n                yield break;\n\n            yield return null;\n''',
'keep reservation alive')

old = '''    private void ReleaseTurretOnce(TurretReservation res) {\n        if (res.Acquired && !res.Released) {\n            res.Released = true;\n            res.Acquired = false;\n            if (ReferenceEquals(_fireLaneCommittedTask, res.Task))\n                _fireLaneCommittedTask = null;\n            _turretLock.Release();\n        }\n    }\n'''
new = '''    private void ReleaseTurretOnce(TurretReservation res) {\n        if (res.Acquired && !res.Released) {\n            res.Released = true;\n            res.Acquired = false;\n            res.Ready = false;\n            res.HardCommitted = false;\n            if (ReferenceEquals(_turretLaneOwnerTask, res.Task))\n                _turretLaneOwnerTask = null;\n            if (ReferenceEquals(_fireLaneCommittedTask, res.Task))\n                _fireLaneCommittedTask = null;\n            _turretLock.Release();\n        }\n    }\n'''
replace_once(old, new, 'release turret owner')

# Safety assertions for the intended semantics.
if 'CommitFireLane(task, res.Generation)' in s:
    raise SystemExit('early hard-commit call remains')
if '_firePriorityWinnerProvisional = false;\n        _firePriorityOrderText = $"T{winner.Task.targetId}' in s:
    raise SystemExit('pair winner still hard-fixed')
if 'ReferenceEquals(_fireLaneCommittedTask, _firePriorityWinner)' in s:
    raise SystemExit('second queue still depends on hard commit')
if 'shared fire lane hard-committed before Review Console' not in s:
    raise SystemExit('hard-commit marker missing')
if 'shared turret lane claimed provisionally' not in s:
    raise SystemExit('provisional turret claim marker missing')

p.write_text(s, encoding='utf-8')
